spring.datasource.url=jdbc:postgresql://db:5432/ptir_db
spring.datasource.username=ptir_user
spring.datasource.password=ptir_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update


spring.jpa.show-sql=true

spring.jpa.open-in-view=false